name: Update WakaTime Stats

on:
  schedule:
    - cron: "0 * * * *" 
  workflow_dispatch: 

  
permissions:
  contents: write

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout Repository
        uses: actions/checkout@v3


      - name: Update WakaTime Readme Stats
        uses: athul/waka-readme@v2.2.0
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPOSITORY: rithish72/rithish72
          SHOW_TITLE: true 
          LANG_COUNT: 5
          TIME_RANGE: last_7_days 
          SHOW_TIME: true 
          SHOW_TOTAL: false 
          
